---
- name: Edit sshd_config and add a new banner file
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Create the banner file containing the warning message and official NU LOGO
      copy:
        dest: /etc/ssh/my_banner
        content: |
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%########%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##%%%%%***#%#%%%###%%%##%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%##%%%#*#%%#%%%%%%%%%%%%%%#%%%###%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%#%%%##%#%#%%%%%%%%%%%%%%%%%%%%%%%%%###%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%#*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%#%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*%%%#%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%#%##%%%%%%%%%===*%%%%%%%%%%*==*%%%%*==+%%%%%%%%%%%+==*%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%#%%#%%%%%%%%%%*#==*%%%%%%%%%%*+%%%%%%==*%%%%%%%%%%%#=+#%%%%%%%###%%#%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%#%%%%%%%%%%%*%%==+%%%%%%%%%%+%%%%%%==#%%%%%%%%%%%#=+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%#%%#%%%%%%%%%%%*%%%+==%%%%%%%%%*%%%%%%==#%%%%%%%%%%%%=+%%%%%%%%%###%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%#%%%%%%%%%%%%*%%%%*==%%%%%%%%#%%%%%%==#%%%%%%%%%%%%=+%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%#%%+%%%%%%%%%%%%*%%%%%*==*%%%%%%#%%%%%%==#%%%%%%%%%%%%=+%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%#%%*%%%%%%%%%%%%*%%%%%%#==*%%%%%#%%%%%%==#%%%%%%%%%%%%=+%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%#%%#%%%%%%%%%%%%*%%%%%%%%+=+%%%%#%%%%%%==#%%%%%%%%%%%%=+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%#%%#%%%%%%%%%%%%*%%%%%%%%%+=+%%%#%%%%%%==#%%%%%%%%%%%%=+%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%#%%*%%%%%%%%%%%%+%%%%%%%%%%*==#%#%%%%%%==#%%%%%%%%%%%#=+%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%*%%%%%%%%%%%%+%%%%%%%%%%%#==*#%%%%%%+=*%%%%%%%%%%%#=*%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%#%%%%%%%%%%%@=+%%%%%%%%%%%#==+%%%%%%#=+%%%%%%%%%%%+=#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%#%%*%%%%%%%%%%%==*%%%%%%%%%%%%++%%%%%%%%++%%%%%%%%%++%%%%%%%%%%%%#+%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%#%%#%%%%%%%%%%###%%%%%%%%%%%%%#%%%%%%%%%%%%#***#%%%%%%%%%%%%%%%%*%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%% !!!!WARNING!!!!! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%###%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%THIS DEVICE IS OWNED & MANAGED BY NU-HQ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%% UNAUTHORIZED ACCESS IS STRICTLY PROHIBITED %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*%%#%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%#%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%*%%#%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%#%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%#%%###%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%###%%%%%%%%%%%%%%%%%%%%%%%%%%%%###%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%####%%%%%%%%%%%%%%%%%%####%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%############%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


    - name: Ensure the banner file is referenced in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Banner'
        line: 'Banner /etc/ssh/my_banner'
        state: present

    - name: Restart SSH service to apply changes
      service:
        name: sshd
        state: restarted
