---
- hosts: all

  become: true
  become_method: sudo

  tasks:
    - name: Install Wazuh Agent & Add Agent to the Wazuh Manager
      ansible.builtin.raw: wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_amd64.deb && sudo WAZUH_MANAGER='{{wazuh_manager_ip}}' dpkg -i ./wazuh-agent_4.9.2-1_amd64.deb
      
    - name: Enable & Start the Wazuh-agent
      ansible.builtin.raw:  sudo systemctl daemon-reload && sudo systemctl enable wazuh-agent && sudo systemctl start wazuh-agent
