---
- hosts: all

  become: true
  become_method: sudo

  tasks:
    - name: APT Package Upgrade
      apt:
        upgrade: yes

    - name: APT Cache Update
      apt:
        update_cache: yes

    - name: Manual Upgrade[Covers any missed upgrades]
      ansible.builtin.raw: sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y
      
    - name: Reboot the Server to apply updates
      reboot:
        test_command: uptime
        reboot_timeout: 3600
