---
- hosts: all
  tasks:

    - name: Log lines to MS Teams
      tags:
      - alert
      - msteams
      - send_msteams
       
      uri:
        url: "{{webhook_url}}"
        method: POST
        status_code: 200
        body_format: json
        body: "This is a test email"
