---
- hosts: all
  tasks:
  
    ## Here you run the automation tasks and capture the output as required to populate the payload

    - name: Send a notification to Teams Channel
      uri:
        ## Use your own URL here
        url: "{{webhook_url}}"
        method: POST
        body_format: json
        body:
          title: "IaaS provisioning job"
          text: "IaaS request has completed. Details of VMs created:"
