---
- hosts: all
  tasks:

    - name: Log lines to MS Teams
      message: " {{ output.stdout }}" 
      uri:
        url: "{webhook_url}"
        body: "{{ message }}"
        body_format: json
        method: POST
