---
- hosts: all
  tasks:

    - name: Log lines to MS Teams
       
      uri:
        url: "{webhook_url}"
        message: " {{ output.stdout }}"
        body: "{{ message }}"
        body_format: json
        method: POST
