---
- hosts: all
  tasks:

    - name: Log lines to MS Teams
      tags:
      - alert
      - msteams
      - send_msteams
       
      office_365_connector_card:
        webhook: "{{webhook_url}}"
        text: "we're good"
