---
- hosts: all

  become: true
  become_method: sudo

  tasks:
  vars:
    ## These variables would be generated dynamically as part of your workflow
    JOB_NAME: "Update PiHole Servers"

  tasks:
    - name: Update Gravity Database
      ansible.builtin.raw: sudo pihole -g
      
    - name: Update PiHole
      ansible.builtin.raw: sudo pihole -up

    - name: Reboot the PiHole Server to apply updates
      reboot:
        test_command: uptime
        reboot_timeout: 3600
