---
- hosts: all
  ## Notes: This script assumes you're logged in as the staging user. You're now adding the automation account.

  become: true
  become_method: sudo
  
  tasks:
  vars:
    ## These variables would be generated dynamically as part of your workflow
    JOB_NAME: "Prep New Container For Automations"
    
  tasks:
    - name: APT Package Upgrade
      apt:
        upgrade: yes

    - name: APT Cache Update
      apt:
        update_cache: yes
        
    - name: Update Time to NY EST Timezone
      ## Updates the time on the server to EST
      ansible.builtin.raw: sudo timedatectl set-timezone America/New_York

    - name: Create the automation user
      ansible.builtin.user:
        name: "{{automationuser_username}}"
        comment: "{{automationuser_name}}"
        password: "{{automationuser_password}}"
        group: "{{automationuser_group}}"

    - name: Create the admin user -- needed if you want to create a local admin account
      ansible.builtin.user:
        name: "{{newuser_username}}"
        comment: "{{newuser_name}}"
        password: "{{newuser_password}}"
        group: "{{newuser_group}}"
    
    - name: Manual Upgrade
      ## code to force full upgrade. This is helpful if any was missed.
      ansible.builtin.raw: sudo apt update && apt upgrade -y && apt dist-upgrade -y

    - name: Reboot Linux Machine
      ## reboots machine to ensure that all updates & configs have been applied
      reboot:
        test_command: uptime
        reboot_timeout: 3600
        
    - name: Update User Shell
      ## Updates the new user' shell to the preferred choice
      ansible.builtin.command: usermod --shell {{preferred_shell}} {{newuser_username}}
